"""Repository interface protocols for all database aggregates."""

from dataclasses import dataclass
from datetime import date
from typing import Any, Protocol


class UserRepository(Protocol):
    async def get_by_id(self, user_id: str) -> dict[str, Any] | None: ...
    async def get_by_phone(self, phone: str) -> dict[str, Any] | None: ...
    async def save(self, user_data: dict[str, Any]) -> dict[str, Any]: ...


class FarmRepository(Protocol):
    async def get_by_id(self, farm_id: str) -> dict[str, Any] | None: ...
    async def get_by_farmer_id(self, farmer_id: str) -> list[dict[str, Any]]: ...
    async def save(self, farm_data: dict[str, Any]) -> dict[str, Any]: ...
    async def update(self, farm_id: str, updates: dict[str, Any]) -> dict[str, Any] | None: ...


class LandParcelRepository(Protocol):
    async def get_by_id(self, parcel_id: str) -> dict[str, Any] | None: ...
    async def get_by_farm_id(self, farm_id: str) -> dict[str, Any] | None: ...
    async def get_pending_queue(self, district: str | None = None) -> list[dict[str, Any]]: ...
    async def save(self, parcel_data: dict[str, Any]) -> dict[str, Any]: ...
    async def update_status(self, parcel_id: str, status: str, boundary: dict[str, Any] | None = None) -> dict[str, Any] | None: ...


class CaseRepository(Protocol):
    async def get_by_id(self, case_id: str) -> dict[str, Any] | None: ...
    async def get_by_farm_id(self, farm_id: str) -> list[dict[str, Any]]: ...
    async def get_agronomist_queue(self, status: str | None = None) -> list[dict[str, Any]]: ...
    async def save(self, case_data: dict[str, Any]) -> dict[str, Any]: ...
    async def update_status(self, case_id: str, status: str, resolution: dict[str, Any] | None = None) -> dict[str, Any] | None: ...


class AdvisoryRepository(Protocol):
    async def get_by_id(self, advisory_id: str) -> dict[str, Any] | None: ...
    async def get_by_farm_id(self, farm_id: str) -> list[dict[str, Any]]: ...
    async def save(self, advisory_data: dict[str, Any]) -> dict[str, Any]: ...


class HealthRepository(Protocol):
    async def get_latest_by_farm_id(self, farm_id: str) -> dict[str, Any] | None: ...
    async def get_history_by_farm_id(self, farm_id: str) -> list[dict[str, Any]]: ...
    async def save_snapshot(self, snapshot_data: dict[str, Any]) -> dict[str, Any]: ...


class SchemeRepository(Protocol):
    async def get_by_id(self, scheme_id: str) -> dict[str, Any] | None: ...
    async def list_active_schemes(self) -> list[dict[str, Any]]: ...
    async def match_schemes(self, crop: str, category: str, acres: float) -> list[dict[str, Any]]: ...


class AssetRepository(Protocol):
    async def get_by_id(self, asset_id: str) -> dict[str, Any] | None: ...
    async def save(self, asset_data: dict[str, Any]) -> dict[str, Any]: ...


@dataclass(frozen=True)
class RetrievedChunk:
    """One corpus chunk returned by similarity search, with its score.

    Decoupled from the ``KnowledgeChunk`` ORM model so callers (and tests)
    never need a live Postgres/pgvector connection to work with retrieval
    results.
    """

    doc_id: str
    title: str
    reviewed_on: date
    chunk_text: str
    score: float  # cosine similarity in [0.0, 1.0]; 1.0 = identical


class KnowledgeChunkReader(Protocol):
    """Read-only similarity search over the curated RAG corpus (PRD §5.7)."""

    async def similarity_search(self, query_embedding: list[float], top_k: int) -> list[RetrievedChunk]: ...
