"""Core configuration, security, database, enums, and error handling."""

from app.core.config import Settings, get_settings, settings
from app.core.db import AsyncSessionLocal, engine, get_db
from app.core.enums import (
    AssetKind,
    CaseStatus,
    FollowupResponse,
    GateOutcome,
    HealthBand,
    LandStatus,
    ProblemSeverity,
    ProblemStatus,
    SchemeStatus,
    SubIndexKey,
    UserRole,
)
from app.core.errors import (
    AppError,
    BelowConfidenceGateError,
    ForbiddenError,
    LandNotVerifiedError,
    NoRelevantSourceError,
    NotFoundError,
    NotImplementedAPIError,
    OfficerUnavailableError,
    UnauthenticatedError,
    ValidationError,
    register_error_handlers,
)
from app.core.security import (
    create_access_token,
    decode_access_token,
    get_password_hash,
    require_roles,
    verify_password,
)

__all__ = [
    "settings",
    "get_settings",
    "Settings",
    "engine",
    "AsyncSessionLocal",
    "get_db",
    "LandStatus",
    "HealthBand",
    "SubIndexKey",
    "ProblemSeverity",
    "ProblemStatus",
    "FollowupResponse",
    "CaseStatus",
    "SchemeStatus",
    "AssetKind",
    "UserRole",
    "GateOutcome",
    "AppError",
    "UnauthenticatedError",
    "ForbiddenError",
    "NotFoundError",
    "ValidationError",
    "LandNotVerifiedError",
    "BelowConfidenceGateError",
    "NoRelevantSourceError",
    "OfficerUnavailableError",
    "NotImplementedAPIError",
    "register_error_handlers",
    "verify_password",
    "get_password_hash",
    "create_access_token",
    "decode_access_token",
    "require_roles",
]
